### ISSUE TITLE
The old test runner results are being cached and interfere with the tests run in another instance of the editor

### ISSUE THREAD

**Issue by ross-u** [ironhack-labs/lab-dom-ironhack-cart#2058]
Not sure if this is related to VSCode or to the test runner, but I had the following issue.
After cloning the LAB and installing and running the tests with `npm run test:watch` for the first time, everything works fine.

After closing the process and creating and running a copy of the same LAB repository (cloning again the LAB, installing packages and running `npm run test:watch`), the tests that are run in the new repository show the results from the previous repository and the last run, as if the entire content is cached.

I tried adding the `--no-cache` flag to the `npm run test:watch` command, but this didn't solve the issue.

@josecarneiro Any idea why this is happening?

**Comment by josecarneiro** [comment]
Hi @ross-u, I'm currently afk but will look into this later today/early tomorrow morning and I'll update you on any findings, there should be a workaround here. Thank you for the heads up!
