### ISSUE TITLE
index.js is not linked correctly in index.html

### ISSUE THREAD

**Issue by binghatch** [ironhack-labs/lab-dom-ironhack-cart#2913]
Currently, there is one script linked in `index.html` on _line 57_. The `src` attribute of this script is currently pointing to `./js/index.js`. **The folder `./js` doesn't exist.**

**Instead, the `src` attribute of the script should link to `./src/index.js`.**

**Comment by ironhack-edu** [comment]
This issue was fixed in the previous iteration. Thank you for reporting.
